debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fc.projectboard: debug
    org.springframework.web.servlet: debug # ? ?? ??/?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace # ?? ?? ? ? ??

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: uno
    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver // 자동으로 세팅 해준다.
#      url: jdbc:h2:mem:testdb
#      username: sa
#      driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true # sql
    properties:
      hibernate: # hibernate ORM (properties)
        format_sql: true # 한줄쿼리를 보기 좋게 포맷
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false #
  sql:
    init:
      mode: always #
  # thymeleaf.cashe: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


---
#cloudtype
spring:
  config:
    activate:
      on-profile: ${PROFILE}
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#    test:
#      database:
#        replace: none