debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fc.projectboard: debug
    org.springframework.web.servlet: debug # ? ?? ??/?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace # ?? ?? ? ? ??

spring:
  prifiles:
    active: ${PROFILE}
  datasource:
#    url: jdbc:mysql://localhost:3306/board
#    username: uno
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/board
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:h2:mem:testdb
#      username: sa
#      driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true # sql
    properties:
      hibernate: # hibernate ORM (properties)
        format_sql: true # 한줄쿼리를 보기 좋게 포맷
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false #
  sql:
    init:
      mode: always #
  # thymeleaf.cashe: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
---


spring:
  config:
    activate:
      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#    test:
#      database:
#        replace: none